config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasks.urls',namespace='tasks')),
]

tasks/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "tasks"

urlpatterns = [
    path("", TemplateView.as_view(template_name="tasks/home.html"), name="home"),
    path("help/", TemplateView.as_view(template_name="tasks/help.html"), name="help"),
    path("tasks/", views.TaskListView.as_view(), name="task_list"),
    path("tasks/create/", views.TaskCreateView.as_view(), name="task_create"),
    path("tasks/<int:pk>/", views.TaskDetailView.as_view(), name="task_detail"),
    path("tasks/<int:pk>/edit/", views.TaskUpdateView.as_view(), name="task_update"),
    path("tasks/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    STATUS_CHOICE = [
        ("UNASSIGNED", "Unassigned"),
        ("IN_PROGRESS", "In Progress"),
        ("DONE", "Done"),
        ("ARCHIVED", "Archived"),
    ]
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=False, default=" ")
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICE, default="UNASSIGNED"
    )
    db_comment = "Can be UNASSIGNED , IN_PROGRESS, DONE , or ARCHIVED"
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_tasks", on_delete=models.CASCADE
    )
    owner = models.ForeignKey(
        User,
        related_name="owned_tasks",
        on_delete=models.SET_NULL,
        null=True,
        db_column="foreign Key to the User who currently owns the task",
    )
    epic = models.ForeignKey("Epic", on_delete=models.SET_NULL, null=True)
    due_date = models.DateField(null=True)

    class Meta:
        db_table_comment = "Holds information about tasks"
        constraints = [
            models.CheckConstraint(
                condition=models.Q(status="IN_PROGRESS")
                | models.Q(status="done")
                | models.Q(status="UNASSIGNED")
                | models.Q(status="ARCHIVED"),
                name="check_status",
            ),
            models.CheckConstraint(
                condition=models.Q(created_at__lt=models.F("due_date")),
                name="check due date",
            ),
        ]


class Sprint(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_sprints", on_delete=models.CASCADE
    )
    tasks = models.ManyToManyField("Task", related_name="sprints", blank=True)

    class Meta:
        constraints = [
            models.CheckConstraint(
                condition=models.Q(end_date__gt=models.F("start_date")),
                name="end_date_after_start_date",
            )
        ]


class Epic(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_epics", on_delete=models.CASCADE
    )

tasks/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic import CreateView, UpdateView, DeleteView
from .models import Task
from .mixins import SprintTaskMixin


class TaskListView(ListView):
    model = Task
    template_name = "tasks/task_list.html"
    context_object_name = "tasks"


class TaskDetailView(DetailView):
    model = Task
    template_name = "tasks/task_detail.html"
    context_object_name = "task"


class TaskDeleteView(DeleteView):
    model = Task
    template_name = "tasks/task_confirm_delete.html"
    success_url = reverse_lazy("tasks:task_list")


class TaskCreateView(CreateView):
    model = Task
    template_name = "tasks/task_form.html"
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy("tasks:task_detail", kwargs={"pk": self.object.id})


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/task_form.html"
    fields = "__all__"
    
    def get_success_url(self):
        return reverse_lazy("tasks:task_detail", kwargs={"pk": self.object.id})

templates/_footer.html
<div class="container">
  <footer class="footer mt-auto py-3 bg-light text-center">
    <div class="container">
      <a href="/help" class="text-dark">Help</a>
    </div>
  </footer>
</div>

templates/_header.html
<div class="container">
  <header class="d-flex justify-content-between align-items- center p-3">
    <!-- Left side -->
    <div>
      <a href="{% url "tasks:task_create" %}" class="btn btn-primary">Create</a>
    </div> <!-- Right side --> <div class="d-flex">
      <input type="text" class="form-control" id="search" placeholder="Search" />
      <button type="button" class="btn btn-success ml- 2">Search</button>
    </div>
  </header>
</div>

templates/base.html
<!DOCTYPE html> <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial- scale=1.0" />
    <title>Task Manager</title> <!-- CSS files --> <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous" />
    <!-- <link rel="stylesheet" href="styles.css"> -->
  </head>
  <body>
    {% include '_header.html' %}
    <main>
      <div class="container">
        <a href="{% url "tasks:task_list" %}">show all tasks</a>
        {% block content %}

        {% endblock %}
      </div>
    </main>

    {% include '_footer.html' %}
    <!-- JS files --> <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <!-- <script src="script.js"></script> -->
  </body>
</html>

templates/tasks/help.html
{% extends 'base.html' %}
{% block content %}
  <div class="container mt-4">
    <div class="card">
      <div class="card-header">Help Page</div>
      <div class="card-body">
        <h5 class="card-title">What is a task manager?</h5>
        <p class="card-text">A task management system is software that helps users organize and track the progress of tasks.</p>
        <a href="/" class="btn btn-primary">Go Home</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/home.html
{% extends "base.html" %} 
{% block content %} 
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor …</p>
 {% endblock %}

templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Task</h1>
  <p>Are you sure you want to delete the task "{{ task.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>
  <a href="{% url 'tasks:task_detail' task.id %}">No, take me back</a>
{% endblock %}

templates/tasks/task_detail.html
{% extends 'base.html' %}
{% block content %}
  <h2 class="display-6">Detail of Task Here</h2>

  <p>
    <a href="">{{ task.title|capfirst }}</a>
  </p>
  <p>{{ task.description }}</p>

  <br />
  <a href="{% url 'tasks:task_update' task.id %}">Edit</a>
  <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>
{% endblock %}

templates/tasks/task_form.html
{% extends 'base.html' %}
{% block content %}
  <h1>New Task</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% block content %}
<h2 class="display-6">All Task Here</h2>
<ul>
    {% for task in tasks %}
    <li><a href="{% url "tasks:task_detail" task.id %}">{{task.title|capfirst}}</a></li>
    {% endfor %}
</ul>
<br>

{% endblock content %}